// Created by Ronis Vision. All rights reserved
// 28.06.2020 01:58:37
// ======AUTOGENERATED - DONT EDIT======

using System;
using RVLoadBalancer;
using RVModules.RVLoadBalancer;
using UnityEngine;
using Object = UnityEngine.Object;
using RVModules.RVSmartAI;

public interface ILoadBalancedTask 
{
#region Properties
         bool IsRunning { get; }
         Action<float> Action { get; }
         string Name { get; }
         int Priority { get; }
         Action OnTaskStart{ get; set; }
         Action OnTaskFinish{ get; set; }
         string Layer{ get; set; }
         LoadBalancerConfig BalancerConfig { get; }
#endregion
#region Methods
         void StartTask();
         void StartTask(LoadBalancerConfig frequency);
         void StartTask(int frequency);
         void FinishTask();
#endregion
}