// Created by Ronis Vision. All rights reserved
// 28.06.2020 01:48:17
// ======AUTOGENERATED - DONT EDIT======

using System;
using RVLoadBalancer;
using RVModules.RVLoadBalancer;
using UnityEngine;
using Object = UnityEngine.Object;
using RVModules.RVSmartAI;

public interface ILoadBalancedTaskBase 
{
#region Properties
#endregion
#region Methods
#endregion
}